### PR TITLE
feat: Initial Rails app

### PR DESCRIPTION
**Pull request by martintomas**
Initial commit with Rails application. Contains basic stuff plus some extra libs which will be required here -- rswag, postgis, cancancan, rgeo, etc.

I believe we will want to reuse as much as possible code from Heco so I setup Fora same way (and used same gems :)).

Feel free to merge @agnessa @tiagojsag if you don't see any mandatory issues with this.

### CODE REVIEW

**Comment by martintomas** [comment]
> bot

Can we turn off vercel for backend @mbarrenechea ?

**Comment by agnessa** [comment]
Great, looks very familiar :) I think we are going to need sidekiq, unless you suggest sth else for processing uploads in the backoffice? I think it needs to go in a background job. I know we're nowhere near starting the backoffice, but since @tiagojsag is setting up the deployment script, it might be good to add it right away so he can configure that.

**Comment by martintomas** [comment]
> Great, looks very familiar :) I think we are going to need sidekiq, unless you suggest sth else for processing uploads in the backoffice? I think it needs to go in a background job. I know we're nowhere near starting the backoffice, but since @tiagojsag is setting up the deployment script, it might be good to add it right away so he can configure that.

Sure, I can add sidekiq and redis gem. I was not sure how huge these imports are gonna be so kept open to idea that we will maybe not need job, but I guess there is high probability that it will be needed 🙃

**Comment by martintomas** [comment]
I am not sure how you handle error tracking at rails apps so not added any gem responsible for this, but if you plan to use for example `sentry` or some other solution, let me know and I can help you to add appropriate gems ;)

**Review by agnessa — APPROVED** [review]

**Pull request merged**
